### ISSUE TITLE
getDetectedSrid throws exception with xyz file

### ISSUE THREAD

**Issue by kok-foong** [cambridge-cares/TheWorldAvatar#1140]
This was working previously before the recent changes.

Exception:
```
Exception in thread "main" java.lang.RuntimeException: Docker exec command returned '1' and wrote the following to stderr:
 ERROR 1: ERROR - failed to load SRS definition from /stack_scratch/tmp12692676379059526317/dgm1_32396_5447_1_rp.xyz
     at com.cmclinnovations.stack.clients.docker.ContainerClient.handleErrors(ContainerClient.java:125)
     at com.cmclinnovations.stack.clients.gdal.GDALClient.getDetectedSrid(GDALClient.java:212)
     at com.cmclinnovations.stack.clients.gdal.GDALClient.addCustomCRStoPostGis(GDALClient.java:181)
     at com.cmclinnovations.stack.clients.gdal.GDALClient.convertRastersToGeoTiffs(GDALClient.java:338)
     at com.cmclinnovations.stack.clients.gdal.GDALClient.uploadRasterFilesToPostGIS(GDALClient.java:154)
     at com.cmclinnovations.stack.clients.core.datasets.Raster.loadData(Raster.java:27)
     at com.cmclinnovations.stack.clients.core.datasets.PostgresDataSubset.loadInternal(PostgresDataSubset.java:49)
     at com.cmclinnovations.stack.clients.core.datasets.GeoServerDataSubset.loadInternal(GeoServerDataSubset.java:12)
     at com.cmclinnovations.stack.clients.core.datasets.DataSubset.load(DataSubset.java:55)
     at com.cmclinnovations.stack.clients.core.datasets.DatasetLoader.lambda$loadData$6(DatasetLoader.java:150)
     at java.base/java.util.ArrayList.forEach(Unknown Source)
     at com.cmclinnovations.stack.clients.core.datasets.DatasetLoader.loadData(DatasetLoader.java:150)
     at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
     at com.cmclinnovations.stack.clients.core.datasets.DatasetLoader.uploadInputDatasets(DatasetLoader.java:69)
     at com.cmclinnovations.stack.DataUploader.main(DataUploader.java:12)
```
config:
```
{
    "name": "elevation",
	"skip": false,
    "database": "postgres",
    "workspace": "dispersion",
    "datasetDirectory": "elevation",
    "dataSubsets": [
        {
            "type": "raster",
            "name": "elevation",
			"subdirectory": "subdir",
            "skip": false,
            "geoServerSettings": {
                "layerSettings": {
                    "defaultStyle": "dispersion:elevation"
                }
            },
            "gdalTranslateOptions": {
                "sridIn": "EPSG:32632",
				"sridOut": "EPSG:4326"
            }
        }
    ],
	"styles": [
	    {
		    "name": "elevation",
		    "file": "elevation.sld"
	    }
	]
}
```

**Comment by Ushcode** [comment]
I will look into this

**Comment by Ushcode** [comment]
Could you share the elevation data you were using? I was able to upload the raster files from [uk gov site](https://environment.data.gov.uk/survey) but there are no `.xyz` files in that set

**Comment by gpeb2** [comment]
@Ushcode, `.xyz` files are just CSVs so don't contain any metadata so the GDAL error is to be expected.
For me the two options seem to be to either:

1. Gracefully continue if the rasters don't define their SRS/CRS and that GDAL call fails.
2. Skip the custom CRS code if the user has specified the `"sridIn"` under ` "gdalTranslateOptions"`.

I'd probably favour option 2 as specifying the `"sridIn"` already effectively indicates that the rasters don't implicitly know their (correct) CRS.

**Comment by Ushcode** [comment]
Sounds good I can make that change and rebuild @kok-foong I'll let you know when it's good to test
