### ISSUE TITLE
Sometimes the Ontop container stops for no reason without error messages

### ISSUE THREAD

**Issue by gpeb2** [cambridge-cares/TheWorldAvatar#270]

**Comment by markushofmeister** [comment]
Ontop service seems to become unresponsive after 1) the container has been running for a while and/or 2) queries have been repeatedly send to the endpoint:

`Traceback (most recent call last):
  File "/app/agent/kgutils/stackclients.py", line 46, in performQuery
    response = self.ontop_client.execute(query)
  File "/usr/local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1305, in _call_
    answer, self.gateway_client, self.target_id, self.name)
  File "/usr/local/lib/python3.7/site-packages/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o325.execute.
: uk.ac.cam.cares.jps.base.exception.JPSRuntimeException: Error occurred during SPARQL query evaluation
	at uk.ac.cam.cares.jps.base.query.RemoteStoreClient.executeQuery(RemoteStoreClient.java:476)
	at uk.ac.cam.cares.jps.base.query.RemoteStoreClient.execute(RemoteStoreClient.java:434)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.sql.SQLException: Error occurred during SPARQL query evaluation
	at org.apache.jena.jdbc.statements.JenaStatement.executeQuery(JenaStatement.java:411)
	at org.apache.jena.jdbc.statements.JenaStatement.executeQuery(JenaStatement.java:573)
	at uk.ac.cam.cares.jps.base.query.RemoteStoreClient.executeQuery(RemoteStoreClient.java:470)
	... 12 more
Caused by: HttpException: -1 Unexpected error making the query: GET http://kings-lynn-ontop:8080/sparql/?query=SELECT%20%20?station%20?wkt%0AWHERE%0A%20%20%7B%20FILTER%20%28%20?station%20IN%20%28%3Chttps://www.theworldavatar.com/kg/ontoems/ReportingStation_e54c24b2-900d-468a-9ae8-c6e59842c1a6%3E%2C%20%3Chttps://www.theworldavatar.com/kg/ontoems/ReportingStation_45a630e2-c3a2-48ce-b029-802f669be5dc%3E%2C%20%3Chttps://www.theworldavatar.com/kg/ontoems/ReportingStation_370ac71c-513b-49f0-9310-5f16dc4d56aa%3E%2C%20%3Chttps://www.theworldavatar.com/kg/ontoems/ReportingStation_5bc49024-71b8-45d8-9549-c344085b9b40%3E%2C%20%3Chttps://www.theworldavatar.com/kg/ontoems/ReportingStation_de194d91-c238-45c6-be9a-c6caf924de9d%3E%2C%20%3Chttps://www.theworldavatar.com/kg/ontoems/ReportingStation_a7516c53-c00e-42f4-9950-8f750c713371%3E%2C%20%3Chttps://www.theworldavatar.com/kg/ontoems/ReportingStation_0793d77c-5bd1-476f-b8a3-7109233bcb47%3E%2C%20%3Chttps://www.theworldavatar.com/kg/ontoems/ReportingStation_3cc7d92f-9f52-4b50-a5d6-428f30d66956%3E%2C%20%3Chttps://www.theworldavatar.com/kg/ontoems/ReportingStation_1d1dda06-70f1-4af7-a284-ea45e97c8577%3E%2C%20%3Chttps://www.theworldavatar.com/kg/ontoems/ReportingStation_a0a239a5-82d2-48aa-ac88-e1343cbe0e65%3E%29%20%29%0A%20%20%20%20?station%20%20a%20%20%3Chttp://www.opengis.net/ont/geosparql%23Feature%3E%20.%0A%20%20%20%20?station%20%3Chttp://www.opengis.net/ont/geosparql%23hasGeometry%3E/%3Chttp://www.opengis.net/ont/geosparql%23asWKT%3E%20?wkt%0A%20%20%7D%0A
	at org.apache.jena.sparql.engine.http.QueryExceptionHTTP.rewrap(QueryExceptionHTTP.java:52)
	at org.apache.jena.sparql.exec.http.QueryExecHTTP.executeQuery(QueryExecHTTP.java:501)
	at org.apache.jena.sparql.exec.http.QueryExecHTTP.performQuery(QueryExecHTTP.java:471)
	at org.apache.jena.sparql.exec.http.QueryExecHTTP.execRowSet(QueryExecHTTP.java:168)
	at org.apache.jena.sparql.exec.http.QueryExecHTTP.select(QueryExecHTTP.java:160)
	at org.apache.jena.sparql.exec.QueryExecutionAdapter.execSelect(QueryExecutionAdapter.java:117)
	at org.apache.jena.jdbc.statements.JenaStatement.executeQuery(JenaStatement.java:351)
	... 14 more
Caused by: java.net.ConnectException
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:561)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:119)
	at org.apache.jena.http.HttpLib.executeJDK(HttpLib.java:554)
	at org.apache.jena.http.auth.AuthLib.authExecute(AuthLib.java:49)
	at org.apache.jena.http.HttpLib.execute(HttpLib.java:536)
	at org.apache.jena.http.HttpLib.execute(HttpLib.java:493)
	at org.apache.jena.sparql.exec.http.QueryExecHTTP.executeQuery(QueryExecHTTP.java:497)
	... 19 more
Caused by: java.net.ConnectException
	at java.net.http/jdk.internal.net.http.common.Utils.toConnectException(Utils.java:1021)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:179)
	at java.net.http/jdk.internal.net.http.Http1Exchange.sendHeadersAsync(Http1Exchange.java:238)
	at java.net.http/jdk.internal.net.http.Exchange.lambda$responseAsyncImpl0$8(Exchange.java:435)
	at java.net.http/jdk.internal.net.http.Exchange.checkFor407(Exchange.java:367)
	at java.net.http/jdk.internal.net.http.Exchange.lambda$responseAsyncImpl0$9(Exchange.java:439)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
	at java.base/java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:946)
	at java.base/java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2266)
	at java.net.http/jdk.internal.net.http.Exchange.responseAsyncImpl0(Exchange.java:439)
	at java.net.http/jdk.internal.net.http.Exchange.responseAsyncImpl(Exchange.java:343)
	at java.net.http/jdk.internal.net.http.Exchange.responseAsync(Exchange.java:335)
	at java.net.http/jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:347)
	at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(MultiExchange.java:388)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
	at java.base/java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:946)
	at java.base/java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2266)
	at java.net.http/jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:378)
	at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsync0$2(MultiExchange.java:293)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(HttpClientImpl.java:153)
	at java.base/java.util.concurrent.CompletableFuture.completeAsync(CompletableFuture.java:2591)
	at java.net.http/jdk.internal.net.http.MultiExchange.responseAsync(MultiExchange.java:246)
	at java.net.http/jdk.internal.net.http.HttpClientImpl.sendAsync(HttpClientImpl.java:632)
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:540)
	... 25 more
Caused by: java.nio.channels.UnresolvedAddressException
	at java.base/sun.nio.ch.Net.checkAddress(Net.java:131)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:673)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$0(PlainHttpConnection.java:165)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:167)
	... 50 more`

**Comment by kokfoongcmcl** [comment]
Try sending the query via blazegraph using the service keyword and see if the issue goes away

**Comment by kokfoongcmcl** [comment]
it looks like the container is down based on java.nio.channels.UnresolvedAddressException at java.base/sun.nio.ch.Net.checkAddress(Net.java:131) at

**Comment by markushofmeister** [comment]
> Try sending the query via blazegraph using the service keyword and see if the issue goes away

How would that exactly look like?

**Comment by kokfoongcmcl** [comment]
where
{SERVICE <ONTOP_ENDPOINT> {YOUR EXISTING QUERY HERE}
}

**Comment by markushofmeister** [comment]
> it looks like the container is down based on java.nio.channels.UnresolvedAddressException at java.base/sun.nio.ch.Net.checkAddress(Net.java:131) at

According to both Portainer and VSCode Docker plugin the container was running. Furthermore, the GUI was "processing" the request, but providing empty results

**Comment by markushofmeister** [comment]
> it looks like the container is down based on java.nio.channels.UnresolvedAddressException at java.base/sun.nio.ch.Net.checkAddress(Net.java:131) at



> where {SERVICE <ONTOP_ENDPOINT> {YOUR EXISTING QUERY HERE} }

That helped to solve similar issues for you previously?

**Comment by kokfoongcmcl** [comment]
> > it looks like the container is down based on java.nio.channels.UnresolvedAddressException at java.base/sun.nio.ch.Net.checkAddress(Net.java:131) at
> 
> > where {SERVICE <ONTOP_ENDPOINT> {YOUR EXISTING QUERY HERE} }
> 
> That helped to solve similar issues for you previously?

Yes

**Comment by markushofmeister** [comment]
> > > it looks like the container is down based on java.nio.channels.UnresolvedAddressException at java.base/sun.nio.ch.Net.checkAddress(Net.java:131) at
> > 
> > 
> > > where {SERVICE <ONTOP_ENDPOINT> {YOUR EXISTING QUERY HERE} }
> > 
> > 
> > That helped to solve similar issues for you previously?
> 
> Yes

So, does that mean you "skip" the Ontop client completly and run all Ontop queries using the SERVICE keyword via Blazegraph?

**Comment by kokfoongcmcl** [comment]
so far it seems to have fixed the ontop connection closed issue, because the current RemoteStoreClient closes the connection (which it's supposed to)
