### ISSUE TITLE
DerivationOutputs unable to handle infinity values

### ISSUE THREAD

**Issue by jb2197** [cambridge-cares/TheWorldAvatar#365]
https://github.com/cambridge-cares/TheWorldAvatar/blob/98df781780dd408d033b16da878fa7e0a9c9341f/JPS_BASE_LIB/src/main/java/uk/ac/cam/cares/jps/base/derivation/DerivationOutputs.java#L187

The literal triple added via `addLiteral("http://s", "http://p", Double.POSITIVE_INFINITY)` will be serialised to `{<http://s> <http://p> Infinity.}` when updating derivation outputs in KG, resulting an invalid SPARQL update string. The valid triple should read `{<http://s> <http://p> "Infinity"^^xsd:double.}`. The same behaviour applies to negative infinity values (`Double.NEGATIVE_INFINITY`), i.e. `{<http://s> <http://p> -Infinity.}` should be corrected to `{<http://s> <http://p> "-Infinity"^^xsd:double.}`.

Potential fix:
```java
public void addLiteral(String s, String p, Number o) {
	s = trimIRI(s);
	p = trimIRI(p);
	try {
		checkIfValidIri(Arrays.asList(s, p));
	} catch (Exception e) {
		throw new JPSRuntimeException(INVALID_IRI_FOR_ADDING_LITERAL + Arrays.asList(s, p, o).toString());
	}
	if (o.equals(Double.POSITIVE_INFINITY)) {
		this.addLiteral(s, p, "Infinity", XSD.DOUBLE.toString());
	} else if (o.equals(Double.NEGATIVE_INFINITY)) {
		this.addLiteral(s, p, "-Infinity", XSD.DOUBLE.toString());
	} else {
		this.outputTriples.add(Rdf.iri(s).has(Rdf.iri(p), Rdf.literalOf(o)));
	}
}
```

**Comment by kokfoongcmcl** [comment]
I can't find a reliable source for the proper way to add this, just https://www.oreilly.com/library/view/xml-schema/0596002521/re63.html, how about integers?

**Comment by kokfoongcmcl** [comment]
I think it's better to use isInfinte()

**Comment by jb2197** [comment]
> just https://www.oreilly.com/library/view/xml-schema/0596002521/re63.html

> I think it's better to use isInfinte()

What about below:
```java
if (o instanceof Double) {
	if (((Double) o).isInfinite()) {
		if (((Double) o) > 0) {
			this.addLiteral(s, p, "INF", XSD.DOUBLE.toString());
		} else {
			this.addLiteral(s, p, "-INF", XSD.DOUBLE.toString());
		}
	} else if (((Double) o).isNaN()) {
		this.addLiteral(s, p, "NaN", XSD.DOUBLE.toString());
	} else {
		this.outputTriples.add(Rdf.iri(s).has(Rdf.iri(p), Rdf.literalOf(o)));
	}
} else {
	this.outputTriples.add(Rdf.iri(s).has(Rdf.iri(p), Rdf.literalOf(o)));
}
```

**Comment by kokfoongcmcl** [comment]
Looks ok, I'd combine isInfinite and the positive check, e.g. isInfinite && >0. 
My only concern now is when you query it, you cannot parse INF directly with the Double class?

**Comment by jb2197** [comment]
It turns out that the above fix works for SPARQL update with `INSERT DATA` clause, however, fails in `INSERT {} WHERE {}` clause if updated on blazegaph-backended triple store (**it works for rdf4j-backended tho**, confirmed by @kokfoongcmcl). 

On blazegraph, if one execute below update,
```sparql
INSERT {
  <http://s> <http://p> "INF"^^xsd:double .
}
WHERE {
  ?s ?p ?o.
}
```
it will try to parse the double from the string `"INF"` using `Double.parseDouble(String)`, which will run into the below exception as `"INF"` is not considered a valid value to be a Double in Java (the correct string should be `"Infinity"`):
```
          ERROR: SPARQL-UPDATE: updateStr=INSERT {
    "INF"^^xsd:double .
}
WHERE {
  ?s ?p ?o.
}

java.util.concurrent.ExecutionException: java.lang.NumberFormatException: For input string: "INF"
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.bigdata.rdf.sail.webapp.BigdataServlet.submitApiTask(BigdataServlet.java:294)
	at com.bigdata.rdf.sail.webapp.QueryServlet.doSparqlUpdate(QueryServlet.java:460)
	at com.bigdata.rdf.sail.webapp.QueryServlet.doPost(QueryServlet.java:241)
	at com.bigdata.rdf.sail.webapp.RESTServlet.doPost(RESTServlet.java:269)
	at com.bigdata.rdf.sail.webapp.MultiTenancyServlet.doPost(MultiTenancyServlet.java:195)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:887)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1684)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NumberFormatException: For input string: "INF"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:543)
	at java.base/java.lang.Double.valueOf(Double.java:506)
	at com.bigdata.rdf.sail.sparql.ASTDeferredIVResolutionInitializer.decode(ASTDeferredIVResolutionInitializer.java:618)
	at com.bigdata.rdf.sail.sparql.ASTDeferredIVResolutionInitializer.getBigdataValue(ASTDeferredIVResolutionInitializer.java:374)
	at com.bigdata.rdf.sail.sparql.ASTDeferredIVResolutionInitializer.process(ASTDeferredIVResolutionInitializer.java:229)
	at com.bigdata.rdf.sail.sparql.Bigdata2ASTSPARQLParser.parseUpdate2(Bigdata2ASTSPARQLParser.java:280)
	at com.bigdata.rdf.sail.webapp.QueryServlet$SparqlUpdateTask.call(QueryServlet.java:533)
	at com.bigdata.rdf.sail.webapp.QueryServlet$SparqlUpdateTask.call(QueryServlet.java:472)
	at com.bigdata.rdf.task.ApiTaskForIndexManager.call(ApiTaskForIndexManager.java:68)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
```

> https://www.oreilly.com/library/view/xml-schema/0596002521/re63.html

The same exception will also be thrown if `"-INF"` is passed in. Although both `"INF"`  and `"-INF"` are valid values in `xsd:double` (in fact, they seem to be _THE_ valid values for infinity), it seems the easiest way, for now, is to use `"Infinity"` and `"-Infinity"` in stead in below two lines, respectively:

change 
> https://github.com/cambridge-cares/TheWorldAvatar/blob/b3d02f4a830a61119c1dfb87c806d04a40eba91d/JPS_BASE_LIB/src/main/java/uk/ac/cam/cares/jps/base/derivation/DerivationOutputs.java#L199

to `this.addLiteral(s, p, "Infinity", XSD.DOUBLE.toString());`

and change
> https://github.com/cambridge-cares/TheWorldAvatar/blob/b3d02f4a830a61119c1dfb87c806d04a40eba91d/JPS_BASE_LIB/src/main/java/uk/ac/cam/cares/jps/base/derivation/DerivationOutputs.java#L201

to `this.addLiteral(s, p, "-Infinity", XSD.DOUBLE.toString()); `

This has been tested work for both blazegraph and rdf4j, the python side is also able to query the added literal and parse it to `inf` using `float('Infinity')`.

What do you think? @sm453

**Comment by sm453** [comment]
As discussed, all things considered, go with "Infinity".
