### ISSUE TITLE
RemoteStoreClient closes the shared connection after each query

### ISSUE THREAD

**Issue by jb2197** [cambridge-cares/TheWorldAvatar#389]
The latest RemoteStoreClient now closes the connection after each query, this causes an issue if an agent is querying from the ontop endpoint repeatedly

_Originally posted by @kokfoongcmcl in https://github.com/cambridge-cares/TheWorldAvatar/issues/388#issuecomment-1285512449_
      

Besides the above issue, if the agent querying from blazegraph endpoint with multi-thread, there exists a situation where the `conn.close()` will affect other queries. An example is `java.sql.SQLException: The Statement is closed` exception below:

```
Traceback (most recent call last):
File "~/twa/TheWorldAvatar/JPS_BASE_LIB/python_derivation_agent/pyderivationagent/kg_operations/sparql_client.py", line 74, in performQuery
response = self.kg_client.execute(query)
File "~/anaconda3/envs/twa/lib/python3.8/site-packages/py4j/java_gateway.py", line 1304, in __call__
return_value = get_return_value(
File "~/anaconda3/envs/twa/lib/python3.8/site-packages/py4j/protocol.py", line 326, in get_return_value
raise Py4JJavaError(
py4j.protocol.Py4JJavaError: An error occurred while calling o9.execute.
: uk.ac.cam.cares.jps.base.exception.JPSRuntimeException: The Statement is closed
at uk.ac.cam.cares.jps.base.query.RemoteStoreClient.executeQuery(RemoteStoreClient.java:476)
at uk.ac.cam.cares.jps.base.query.RemoteStoreClient.execute(RemoteStoreClient.java:434)
at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
at py4j.Gateway.invoke(Gateway.java:282)
at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
at py4j.commands.CallCommand.execute(CallCommand.java:79)
at py4j.GatewayConnection.run(GatewayConnection.java:238)
at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.sql.SQLException: The Statement is closed
at org.apache.jena.jdbc.statements.JenaStatement.executeQuery(JenaStatement.java:556)
at uk.ac.cam.cares.jps.base.query.RemoteStoreClient.executeQuery(RemoteStoreClient.java:470)
... 11 more
```

**Comment by jb2197** [comment]
The line where JenaStatement ran into exception:
https://github.com/apache/jena/blob/91c399148f4f94c19517a88eb8c85db83fdb1342/jena-jdbc/jena-jdbc-core/src/main/java/org/apache/jena/jdbc/statements/JenaStatement.java#L556

The function that is actually called when calling `conn.close()` in RemoteStoreClient, which iterates over all existing statements and closes them:
https://github.com/apache/jena/blob/91c399148f4f94c19517a88eb8c85db83fdb1342/jena-jdbc/jena-jdbc-core/src/main/java/org/apache/jena/jdbc/connections/JenaConnection.java#L455

**Comment by jb2197** [comment]
The `conn.close()` in RemoteStoreClient:
https://github.com/cambridge-cares/TheWorldAvatar/blob/fdc3ad9d21f86e06575ca1595e3c4cc649ebe58e/JPS_BASE_LIB/src/main/java/uk/ac/cam/cares/jps/base/query/RemoteStoreClient.java#L480

**Comment by kokfoongcmcl** [comment]
Closing the connection is a good thing, just that it can be handled better
