### ISSUE TITLE
Stack-Data-Uploader: Error when uploading vector data without a virtual table 

### ISSUE THREAD

**Issue by cmclscourtney** [cambridge-cares/TheWorldAvatar#615]
The following error is given when uploading shapefiles with a virtual table. 
```
Exception in thread "main" java.lang.NullPointerException
        at com.cmclinnovations.stack.clients.core.datasets.Vector.createLayer(Vector.java:27)
        at com.cmclinnovations.stack.clients.core.datasets.GeoServerDataSubset.loadInternal(GeoServerDataSubset.java:13)
        at com.cmclinnovations.stack.clients.core.datasets.DataSubset.load(DataSubset.java:52)
        at com.cmclinnovations.stack.clients.core.datasets.DatasetLoader.lambda$loadData$9(DatasetLoader.java:120)
        at java.base/java.util.ArrayList.forEach(Unknown Source)
        at com.cmclinnovations.stack.clients.core.datasets.DatasetLoader.loadData(DatasetLoader.java:120)
        at com.cmclinnovations.stack.clients.core.datasets.DatasetLoader.uploadInputDatasets(DatasetLoader.java:63)
        at com.cmclinnovations.stack.DataUploader.main(DataUploader.java:12)
```

To recreate use ["cropmap-simple"](https://github.com/cambridge-cares/TheWorldAvatar/blob/main/Deploy/stacks/dynamic/example_datasets/inputs/config/cropmap-simple.json) example to see error and ["cropmap"](https://github.com/cambridge-cares/TheWorldAvatar/blob/main/Deploy/stacks/dynamic/example_datasets/inputs/config/cropmap.json) example to see correct behavior.

Current simple fix is to always have a virtual table with vector data.

**Comment by sm453** [comment]
Simple work-around: Downgrade the stack data uploader docker image version to 1.7.1 in the docker compose file.
