### ISSUE TITLE
Inactive flood warnings not completely removed from visualisation

### ISSUE THREAD

**Issue by markushofmeister** [cambridge-cares/TheWorldAvatar#835]
It has been observed that some floodwarnings do not disappear from the visualisation although they have been removed by EA from the [API](https://environment.data.gov.uk/flood-monitoring/id/floods).
The warnings are successfully deleted from the KG, but the respective flood areas are not set to inactive within PostGIS to disappear from the active warnings within the DTVF.

While the root cause of this needs to be investigated and fixed, a temporary workaround to remove the erroneously shown flood warnings can be achieved by running the following two SQL updates manually:

```
UPDATE floodwarnings
SET severity = 4
WHERE severity IS NULL;
```
```
UPDATE floodwarnings
SET active = False
WHERE active = True;
```

**Comment by markushofmeister** [comment]
The root cause of this issue does not seem to be fully fixed:
```
2023-09-19 05:00:00,001 (STDOUT) Looking for jobs to run
2023-09-19 05:00:00,001 (STDOUT) Next wakeup is due at 2023-09-19 06:00:00+00:00 (in 3599.998486 seconds)
2023-09-19 05:00:00,002 (STDOUT) Running job "update_warnings (trigger: cron[minute='0'], next run at: 2023-09-19 06:00:00 UTC)" (scheduled at 2023-09-19 05:00:00+00:00)
2023-09-19 05:00:01,965 (STDOUT) Instantiating flood warnings and areas ...
2023-09-19 05:00:02,028 (derivation_markup.py:61)[ThreadPoolExecutor-0_0] INFO - Query to retrieve property info: PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> SELECT DISTINCT ?property ?mv WHERE { VALUES ?property { } OPTIONAL { ?property <https://www.theworldavatar.com/kg/ontobuiltenv/hasMarketValue> ?mv. } }
2023-09-19 05:00:02,043 (derivation_markup.py:63)[ThreadPoolExecutor-0_0] INFO - Length of response: 0
2023-09-19 05:00:02,044 (derivation_markup.py:141)[ThreadPoolExecutor-0_0] ERROR - An empty list is passed in while requesting return value of key 'property'.
2023-09-19 05:00:02,044 (STDOUT) Number of affected properties: 0
2023-09-19 05:00:02,044 (derivation_markup.py:36)[ThreadPoolExecutor-0_0] INFO - Query to retrieve flood assessment derivation iri: SELECT DISTINCT ?flood_assessment_derivation WHERE { ?flood_assessment_derivation <https://www.theworldavatar.com/kg/ontoderivation/isDerivedFrom> <http://environment.data.gov.uk/flood-monitoring/id/floods/034WAF430>. ?flood_assessment_derivation <https://www.theworldavatar.com/kg/ontoderivation/isDerivedUsing> <https://www.theworldavatar.com/resource/agents/Service__KL_FloodAssessment/Service>. }
2023-09-19 05:00:02,058 (derivation_markup.py:38)[ThreadPoolExecutor-0_0] INFO - Response: [{'flood_assessment_derivation': 'https://www.theworldavatar.com/kg/derivation/DerivationAsyn_60b38e35-76d6-4511-9269-5ec95284143f'}]
2023-09-19 05:00:02,092 (STDOUT) Job "update_warnings (trigger: cron[minute='0'], next run at: 2023-09-19 06:00:00 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/agent/datainstantiation/warnings.py", line 104, in update_warnings
    instantiate_flood_areas_and_warnings(areas_to_instantiate, areas_kg,
  File "/app/agent/datainstantiation/warnings.py", line 232, in instantiate_flood_areas_and_warnings
    new_warnings = instantiate_flood_warnings(warning_data_to_instantiate, kgclient=kgclient,
  File "/app/agent/datainstantiation/warnings.py", line 385, in instantiate_flood_warnings
    flood_assessment_derivation_markup(
  File "/app/agent/datainstantiation/derivation_markup.py", line 105, in flood_assessment_derivation_markup
    derivation_client.unifiedUpdateDerivation(flood_assessment_derivation_iri)
  File "/usr/local/lib/python3.9/site-packages/pyderivationagent/kg_operations/derivation_client.py", line 368, in unifiedUpdateDerivation
    self.derivation_client.unifiedUpdateDerivation(derivationIRI)
  File "/usr/local/lib/python3.9/site-packages/py4j/java_gateway.py", line 1304, in __call__
    return_value = get_return_value(
  File "/usr/local/lib/python3.9/site-packages/py4j/protocol.py", line 326, in get_return_value
    raise Py4JJavaError(
py4j.protocol.Py4JJavaError: An error occurred while calling o5278.unifiedUpdateDerivation.
: uk.ac.cam.cares.jps.base.exception.JPSRuntimeException: java.util.NoSuchElementException: No value present
        at uk.ac.cam.cares.jps.base.derivation.DerivationClient.unifiedUpdateDerivation(DerivationClient.java:593)
        at jdk.internal.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.NoSuchElementException: No value present
        at java.base/java.util.Optional.get(Optional.java:148)
        at uk.ac.cam.cares.jps.base.derivation.DerivationSparql.getDerivation(DerivationSparql.java:2455)
        at uk.ac.cam.cares.jps.base.derivation.DerivationClient.updateMixedAsyncDerivation(DerivationClient.java:505)
        at uk.ac.cam.cares.jps.base.derivation.DerivationClient.unifiedUpdateDerivation(DerivationClient.java:586)
        ... 10 more
```

**Comment by markushofmeister** [comment]
Temporal fix to delete orphaned flood warnings from KG:

```
prefix deriv: <https://www.theworldavatar.com/kg/ontoderivation/>

delete {
  ?derivation a deriv:DerivationAsyn ;
                deriv:isDerivedFrom ?inputs ;
                deriv:isDerivedUsing ?agent ;
                deriv:retrievedInputsAt ?time ;
                deriv:hasStatus ?status .
  ?status rdf:type ?type ;
          rdfs:comment ?comment 
}
where {
	?derivation a deriv:DerivationAsyn ;
                deriv:isDerivedFrom ?inputs ;
                deriv:isDerivedUsing ?agent ;
                deriv:retrievedInputsAt ?time ;
                deriv:hasStatus ?status .
  ?status rdf:type ?type ;
          rdfs:comment ?comment
}
```

**Comment by markushofmeister** [comment]
Seems closed with PR #934

**Comment by markushofmeister** [comment]
Potentially also relevant flood assessment agent log:

class uk.ac.cam.cares.jps.base.exception.PythonException: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyderivationagent/agent/derivation_agent.py", line 359, in monitor_async_derivations
    self.process_request_parameters(derivation_inputs, derivation_outputs)
  File "/app/floodassessment/agent/impact_assessment.py", line 106, in process_request_parameters
    warning, buildings, estimations = self.validate_input_values(inputs=inputs,
  File "/app/floodassessment/agent/impact_assessment.py", line 66, in validate_input_values
    if len(inp) == 1:
TypeError: object of type 'NoneType' has no len()

java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
py4j.Gateway.invoke(Gateway.java:238)
py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
py4j.GatewayConnection.run(GatewayConnection.java:238)
java.base/java.lang.Thread.run(Thread.java:829)
