### ISSUE TITLE
Data uploader: Unique GeoServer workspace for CityGML data?

### ISSUE THREAD

**Issue by sm453** [cambridge-cares/TheWorldAvatar#974]
Currently, it appears the uploader fails to upload a CityGML dataset if there exists another input config `json` file with the same GeoServer workspace. The error in the uploader docker logs is rather non-obvious:
```
Exception in thread "main" java.lang.RuntimeException: GeoServer database layer '<DATA_SUBSET_NAME>' does not exist and could not be created.
        at com.cmclinnovations.stack.clients.geoserver.GeoServerClient.createPostGISLayer(GeoServerClient.java:208)
        at com.cmclinnovations.stack.clients.core.datasets.CityDB.createLayers(CityDB.java:112)
```
The error goes away simply by changing the GeoServer workspace in the `json` config file for the CityGML dataset.

NB This seems to be specific to CityGML datasets, because for non-CityGML data, many `json` files all uploading to the same GeoServer workspace are known to work just fine.

**Comment by ChungTingLao** [comment]
This happens because CityDB is stored in the "citydb" schema, when geoserver store is set up for the "public" schema only. The same error can happen for two vector datasets if one of them is stored in a schema other than "public". A workaround that allows using one workspace is to explicitly specify any non-"public" schema in the SQL file for the virtual table.
